# Generated by Django 5.0.6 on 2024-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remainder',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Remainder'),
        ),
    ]
