# Generated by Django 5.0.6 on 2024-07-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
