# Generated by Django 5.0.6 on 2024-07-08 11:53

from django.db import migrations
from django.template.defaultfilters import slugify


def get_title_slug(apps, schema_editor):
    Category = apps.get_model('webapp.Category')
    for category in Category.objects.all():
        category.title_slug = slugify(category.title)
        category.save()

def rollback(apps, schema_editor):
    Category = apps.get_model('webapp.Category')
    for category in Category.objects.all():
        category.title_slug = None
        category.save()
class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_category_title_slug'),
    ]

    operations = [
        migrations.RunPython(get_title_slug, rollback),
    ]
